// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxwpljtbznnuqwtvcnsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94d3BsanRiem5udXF3dHZjbnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTY4NTksImV4cCI6MjA3MDE5Mjg1OX0.3vn-CkNH7VBFbRKQgeJXTIvoBDLYROfV835bpgHZLSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});